config/routes.rb
Asr::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :pages, :users, :admin, :manage, :brackets
  resources :divisions do
    resources :brackets
  end
  
  match '/manage', :to => 'manage#index'
  match '/update', :to => 'manage#update'
  match '/rules', :to => 'manage#rules'
  
  match '/contact', :to => 'pages#contact'
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/league', :to => 'pages#league'
  match '/results', :to => 'pages#results'
  match '/prizes', :to => 'pages#prizes'
  match '/news', :to => 'pages#news'
  match '/users', :to => 'users#index'
  match '/users/:id', :to => 'users#show'
  
  match '/alpha', :to => 'pages#alpha'
  match '/beta_i', :to => 'pages#beta_i'
  match '/beta_ii', :to => 'pages#beta_ii'
  match '/gamma_i', :to => 'pages#gamma_i'
  match '/gamma_ii', :to => 'pages#gamma_ii'
  match '/gamma_iii', :to => 'pages#gamma_iii'
  match '/gamma_iv', :to => 'pages#gamma_iv'
  match '/delta', :to => 'pages#delta'
  
  match '/division_form', :to => 'divisions#division_form'
  
  root :to => "pages#home"

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :division
  has_many :users
end

app/controllers/brackets_controller.rb
include SuffixGenerator
include NameGenerator

class BracketsController < ApplicationController
  before_filter :find_division, :only => [:new, :create]
  before_filter :find_bracket, :only => [:show, :destroy]

  def new
    @bracket = Bracket.new :division_id => params[:division_id] # @division.brackets.build
    # @bracket = @division.brackets.build
  end

  def index
    if !user_signed_in?
      redirect_to :root
      flash[:notice] = "Sorry, you must be signed in to view that page."
    end
    
    @divisions = Division.all
    
    @brackets = Bracket.all
    @bracket = Bracket.new
    # redirect_to :action => "create"
  end
  
  def create
    
    @bracket = Bracket.create(params[:bracket])
    @bracket.division_id = params[:division_id]
    @bracket.save
    puts params.inspect
    flash[:success] = "#{@bracket.name} created"
    if params[:commit]
      redirect_to brackets_path
    end
    # render :index
  end
  
  def destroy
    @bracket.destroy
    flash[:success] = "#{@bracket.name} successfully removed"
    
    respond_to do |format|  
      format.html { redirect_to :action => 'index' }  
      format.js   { render :nothing => true }  
    end
    
  end
  
  def show
    
  end
  
  protected
    def find_division
      @division = Division.find(params[:division_id])
    end
    
    def find_bracket
      @bracket = Bracket.find(params[:id])
    end
  
end

app/views/brackets/_bracket.html.erb
  <% division.brackets.each do |b| %>
	<p>Bracket name: <%= b.name %></p>
	(<%= link_to 'Delete', b, :method => :delete, :class => 'delete_link' %>)
  <% end %>

  


	<%= form_for bracket, :html => {:id => "bracket" + "#{bracket.id}"} do |f| %>
	<hr>
	  <div class="actions">
	    <%= f.submit :update %>
	  </div>
	  <span class="ajax_message">
	<% end %>

app/views/brackets/_new.html.erb
<%= form_for @bracket, :url => division_brackets_path(division), :html => {:id => "bracket_create_form"} do |f| %>
  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :create %>
  </div>
  <span class="ajax_message">
<% end %>

app/views/brackets/index.html.erb
<%= provide(:title, "Bracket Management") %>

<table class="table table-striped">
	<thead>
	<tr>
		<th>Division</th>
		<th>Brackets</th>
		<th>Settings</th>
	</tr>
	</thead>
	<tbody>
		<% @divisions.each do |division| %>
		<tr>
			<td><%= division.division_name %></td>
			
		
			<td>
				<p>Division #: <%= division.id %></p>
			<% if !Bracket.find_by_division_id(division.id).nil? %>
				<%= render :partial => 'bracket', :locals => { :bracket => @bracket, :division => division } %>
				<%= render :partial => 'new', :locals => { :division => division } %>
			<% else %>
				<p>No brackets have been created yet.</p>

				<%= render :partial => 'new', :locals => { :division => division } %>
			<% end %>
			</td>
			<td>
			</td>

		</tr>
		<% end %>
	</tbody>
	
</table>

<!-- <script type="text/javascript">
$('#division_form').submit(function() {
             $(this).unbind('submit').submit();
});
</script> -->

app/views/brackets/new.html.erb
<%= form_for @bracket, :html => {:id => "bracket_create_form"} do |f| %>
  <div class="field">
    <p>Bracket name: <%= f.text_field :name %></p>
	<p>Min Players: <%= f.text_field :min_players %></p>
	
	<%= f.hidden_field :division_id %>
  </div>
  <div class="actions">
    <%= f.submit :create %>
  </div>
  <span class="ajax_message">
<% end %>

app/views/brackets/show.html.erb
	<%= link_to @bracket.name %>