config/routes.rb
Asr::Application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  resources :pages, :users, :admin, :manage, :brackets
  resources :divisions do
    resources :brackets
  end
  
  match '/manage', :to => 'manage#index'
  match '/update', :to => 'manage#update'
  match '/rules', :to => 'manage#rules'
  
  match '/contact', :to => 'pages#contact'
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/league', :to => 'pages#league'
  match '/results', :to => 'pages#results'
  match '/prizes', :to => 'pages#prizes'
  match '/news', :to => 'pages#news'
  match '/users', :to => 'users#index'
  match '/users/:id', :to => 'users#show'
  
  match '/alpha', :to => 'pages#alpha'
  match '/beta_i', :to => 'pages#beta_i'
  match '/beta_ii', :to => 'pages#beta_ii'
  match '/gamma_i', :to => 'pages#gamma_i'
  match '/gamma_ii', :to => 'pages#gamma_ii'
  match '/gamma_iii', :to => 'pages#gamma_iii'
  match '/gamma_iv', :to => 'pages#gamma_iv'
  match '/delta', :to => 'pages#delta'
  
  match '/division_form', :to => 'divisions#division_form'
  
  root :to => "pages#home"

end

app/views/layouts/_header.html.erb
	<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Advanced Study Room", root_path, :class => "brand" %>
        <div class="btn-group pull-right">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i><% if user_signed_in? %><%= current_user.kgs_names %>
				<% else %>
					Sign in
				<% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
			<% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <li class="divider"></li>
			<li><%= link_to "My Profile", user_path(current_user.kgs_names) %></li>
			<% else %>
            <li><%= link_to "sign in", new_user_session_path %></li>
			<% end %>
          </ul>
        </div>

        <div class="nav-collapse">
          <ul class="nav nav-pills">
			<% if user_signed_in? %>
				<li><%= link_to "My Profile", user_path(current_user.kgs_names) %></li>

			
			<li class="dropdown" id="menu1">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">Admin Stuff
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Divisions", divisions_path %></li>
					<li><%= link_to "Brackets", brackets_path %></li>
					<li><%= link_to "Rules", rules_path %></li>
					<li><%= link_to "Assign Players", update_path %></li>
				</ul>
			</li>
			<% end %>
			<li class="dropdown" id="menu2">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">League Stuff
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "League", league_path %></li>
					<li><%= link_to "Results", results_path %></li>
					<li><%= link_to "Prizes", prizes_path %></li>
					<li><%= link_to "News", news_path %></li>
				</ul>
			</li>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li></li>
			

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/layouts/_stylesheets.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif] -->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body class="<%= yield(:css_class) %>">
   	

	<%= render 'layouts/header' %>




<div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">

          <div class="hero-unit">
            <h1><%= yield(:title) %></h1>

			
          </div>
					<%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>
					
					<div class="row-fluid">
						<%= yield %>
          
            
          </div><!--/row-->


      <hr>

      <footer>
        <p>&copy; Advanced Study Room 2012</p>
      </footer>

    </div><!--/.fluid-container-->

</body>
</html>